site_name: John Ferri - Docs Portfolio

nav: 
  - Home: index.md
  - SOP: sop-tier1-soc-onboarding.md
  - Playbooks: 
      - Suspicious Login: playbook-suspicious-login.md
      - MFA Fatigue: playbook-mfa-fatigue.md
  - Style Guide: style-guide.md
  - Examples: 
      - Ticket Note Examples: ticket-note-examples.md